### PR TITLE
Fix shortcuts regex

### LINKED ISSUE #187: [Bug/Improvement] Emoji converter
#### What release are you using?
- Release: v1.1.4-alpha

#### Error
The bot gives emoji conversion priority over markdown.

#### Steps required to reproduce the bug
Refer to the screenshot

#### Screenshots (examples)
Expected result: https://imgur.com/VyUo1Qx
Actual result: https://imgur.com/dQPrLH2

#### Improvement
Give markdown priority over emoji conversion. In the examples (screenshots), it should choose to use the star (\*) for markdown instead of an emoji. I think this can be achieved by checking if a markdown pattern is recognized, like double stars (\*\*) or when there is a star (\*) present after a colon (:), check if there is another star somewhere earlier in the message without a colon (:) in front of it. If there is a markdown pattern, skip the conversion of the stars. Or if two stars (\*\*) are present after a colon (:), don't convert the colon and first star to an emoji, but rather give priority to the two stars (\*\*). Another solution would be removing the conversion to an emoji of ':\*'.

The last solution is how I fixed the issue for myself.

### PR DESCRIPTION
**Pull request by Xaliks**
Fixes #187 and format `addMemberList.js`

### CODE REVIEW

File: js/parseMessage.js [hunk 1]
```diff
@@ -17,7 +17,7 @@
...
+        /(?<!\S)(>:\(|>:-\(|>=\(|>=-\(|:"\)|:-"\)|="\)|=-"\)|<\/3|:-\\|:-\/|=-\\|=-\/|:'\(|:'-\(|:,\(|:,-\(|='\(|='-\(|=,\(|=,-\(|:\(|:-\(|=\(|=-\(|<3|♡|]:\(|\]:-\(|]=\(|]=-\(|o:\)|O:\)|o:-\)|O:-\)|0:\)|0:-\)|o=\)|O=\)|o=-\)|O=-\)|0=\)|0=-\)|:'D|:'-D|:,D|:,-D|='D|='-D|=,D|=,-D|:\*|:-\*|=\*|=-\*|x-\)|X-\)|:\||:-\||=\||=-\||:o|:-o|:O|:-O|=o|=-o|=O|=-O|:@|:-@|=@|=-@|:D|:-D|=D|=-D|:'\)|:'-\)|:,\)|:,-\)|='\)|='-\)|=,\)|=,-\)|:\)|:-\)|=\)|=-\)|]:\)|]:-\)|]=\)|]=-\)|:,'\(|:,'-\(|;\(|;-\(|=,'\(|=,'-\(|:P|:-P|=P|=-P|8-\)|B-\)|,:\(|,:-\(|,=\(|,=-\(|,:\)|,:-\)|,=\)|,=-\)|:s|:-S|:z|:-Z|:\$|:-\$|=s|=-S|=z|=-Z|=\$|=-\$|;\)|;-\))(?!\S)/gm;
```
Comment (SebOuellette) [inline js/parseMessage.js:20]: Oh smart

File: js/addMemberList.js [hunk 2]
```diff
@@ -110,51 +106,50 @@ function addMemberList(guild) {
...
-
-                // Make the username text
-                let username = document.createElement('p');
-                username.classList.add('mLUsername');
-                username.innerText = m.nickname || m.user.username;
-                username.style.color = m.roles.color?.hexColor || '#8E9297';
-                userDiv.appendChild(username);
-            });
-    
+    // Display only the first 100 members
```
Comment (SebOuellette) [inline js/addMemberList.js:110]: Oop yeah I fixed this in vim yesterday.. I guess I didn't make sure it was formatted

**Review by SebOuellette — APPROVED** [review]
Looks perfect!
